# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "bootstrap", to: "bootstrap.min.js", preload: true
pin "@popperjs/core", to: "popper.js", preload: true
pin "@cloudinary/url-gen", to: "https://ga.jspm.io/npm:@cloudinary/url-gen@1.13.0/index.js"
pin "@cloudinary/transformation-builder-sdk", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/index.js"
pin "@cloudinary/transformation-builder-sdk/actions", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions.js"
pin "@cloudinary/transformation-builder-sdk/actions/adjust", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/adjust.js"
pin "@cloudinary/transformation-builder-sdk/actions/animated", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/animated.js"
pin "@cloudinary/transformation-builder-sdk/actions/border", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/border.js"
pin "@cloudinary/transformation-builder-sdk/actions/customFunction", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/customFunction.js"
pin "@cloudinary/transformation-builder-sdk/actions/delivery", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/delivery.js"
pin "@cloudinary/transformation-builder-sdk/actions/delivery/DeliveryFormatAction", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/delivery/DeliveryFormatAction.js"
pin "@cloudinary/transformation-builder-sdk/actions/effect", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/effect.js"
pin "@cloudinary/transformation-builder-sdk/actions/namedTransformation", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/namedTransformation.js"
pin "@cloudinary/transformation-builder-sdk/actions/overlay", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/overlay.js"
pin "@cloudinary/transformation-builder-sdk/actions/psdTools", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/psdTools.js"
pin "@cloudinary/transformation-builder-sdk/actions/resize", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/resize.js"
pin "@cloudinary/transformation-builder-sdk/actions/rotate", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/rotate.js"
pin "@cloudinary/transformation-builder-sdk/actions/roundCorners", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/roundCorners.js"
pin "@cloudinary/transformation-builder-sdk/actions/transcode", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/transcode.js"
pin "@cloudinary/transformation-builder-sdk/actions/underlay", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/underlay.js"
pin "@cloudinary/transformation-builder-sdk/actions/videoEdit", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/actions/videoEdit.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/GradientFade", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/GradientFade.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/animatedFormat", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/animatedFormat.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/artisticFilter", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/artisticFilter.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/aspectRatio", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/aspectRatio.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/audioCodec", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/audioCodec.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/audioFrequency", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/audioFrequency.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/background", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/background.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/chromaSubSampling", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/chromaSubSampling.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/color", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/color.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/colorSpace", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/colorSpace.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/dither", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/dither.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/dpr", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/dpr.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/expression", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/expression.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/fontHinting", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/fontHinting.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/fontStyle", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/fontStyle.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/fontWeight", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/fontWeight.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/format", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/format.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/gradientDirection", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/gradientDirection.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/gravity", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/gravity.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/improveMode", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/improveMode.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/outlineMode", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/outlineMode.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/position/PositionQualifier", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/position/PositionQualifier.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/quality", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/quality.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/region", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/region.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/rotationMode", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/rotationMode.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/simulateColorBlind", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/simulateColorBlind.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/source", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/source.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/streamingProfile", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/streamingProfile.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/textAlignment", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/textAlignment.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/textDecoration", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/textDecoration.js"
pin "@cloudinary/transformation-builder-sdk/qualifiers/textStroke", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/qualifiers/textStroke.js"
pin "@cloudinary/transformation-builder-sdk/transformation/ImageTransformation", to: "https://ga.jspm.io/npm:@cloudinary/transformation-builder-sdk@1.8.0/transformation/ImageTransformation.js"
pin "wavesurfer.js", to: "https://ga.jspm.io/npm:wavesurfer.js@7.4.12/dist/wavesurfer.js"
pin "tom-select", to: "tom-select.js"
